site_name: OWIN-JS
theme: readthedocs
repo_url: https://github.com/OWIN-JS/spec/
include_search: true
docs_dir: '.'
site_dir: 'dest'
site_favicon: favicon.ico
pages:
- Home: 'index.md'
- Specification:
    - 'OWIN-JS': 'Specification.md'
- Extensions:
    - 'Common Keys': 'CommonKeys.md'
    - 'Opaque': 'Opaque.md'
    - 'Websocket': 'Websocket.md'
    - 'io.nodekit': 'nodekit.md'
theme:  readthedocs
theme_dir: _theme
