site_name: OWIN-JS
theme: readthedocs
repo_url: https://github.com/OWIN-JS/spec/
include_search: true
docs_dir: '.'
site_dir: 'dest'
site_favicon: favicon.ico
pages:
- ['index.md', 'Home']
- ['Specification.md', 'Specification', 'OWIN-JS']
- ['CommonKeys.md', 'Extensions', 'Common Keys']
- ['Opaque.md', 'Extensions', 'Opaque']
- ['Websocket.md' , 'Extensions', 'Websocket']
- ['nodekit.md' , 'Extensions', 'io.nodekit']
theme:  readthedocs
theme_dir: _theme
